//largestOutOfTwoNumbers
OperationsHelper ppt = new OperationsHelper();
decimal largest = ppt.largestOutOfTwoNumbers(12.5, 20.5);
System.debug('The largest number is ' + largest+ '.');

//smallestOutOfThreeNumbers
decimal smallest = ppt.smallestOutOfThreeNumbers(5, 20, 3);
System.debug('The smallest  number is ' + smallest+ '.');

//sumofPositiveIntegers
decimal summ = ppt.sumofPositiveIntegers(3);
System.debug('The summ of positive numbers is ' + summ+ '.');