Planets ppt = new Planets();
ppt.planetName = 'Mars';
ppt.planetNumber=4;
ppt.moonNumber=2;

system.debug('Planet name is '+ppt.planetName + '. Planet number is ' + ppt.planetNumber + '. Moon number is '+ppt.moonNumber);


Planets earth = new Planets();
earth.planetName = 'Earth';
earth.planetNumber=3;
earth.moonNumber=1;
system.debug('Planet name is '+earth.planetName + '. Planet number is ' + earth.planetNumber + '. Moon number is '+earth.moonNumber);


