public with sharing class gul {
    public void gul() {

        string batchName = 'Falcons4';
integer totalCandidates= 40;
boolean isAdminCompleted= true;
System.debug(batchName);
System.debug(totalCandidates);
System.debug(isAdminCompleted);

string batchDescription = batchName+ ' are the best!';
System.debug(batchDescription);

decimal decValue=27.01;
long longValue=21474836454L;

System.debug(decValue+ '----'+ longValue);

object newobj = 'hello from object';
object newobjWithNumber=6;


id sfid= '00Q5f000005bMw5EAE';

System.debug(sfid);
System.debug(newobj);
System.debug(newobjWithNumber);


    }
}
